name: "Run Python Script"
description: "Run a custom python snippet inside a workflow file"
inputs:
  script:
    description: "Python script"
    required: true
  fail-on-error:
    description: "Fail step if the return code from running the script is non-zero"
    required: false
    default: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "purple"
  icon: "play"
